openapi: 3.0.2
info:
  title: Normal API Endpoints
  description: 正常使用的 API 端點列表
  version: 1.0.0
servers:
  - url: http://apitest.ryantseng.work
    description: Production server
paths:
  /:
    get:
      summary: 根目錄
      description: 返回 API 平台基本資訊
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "API Security Test Platform. See /docs for API list."
  /api1/user/{user_id}:
    get:
      summary: 獲取用戶資料
      description: 根據用戶 ID 獲取用戶資料
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  data:
                    type: string
  /api2/login:
    post:
      summary: 用戶登入
      description: 使用用戶名和密碼進行登入
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: 登入成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  token:
                    type: string
  /api2/profile:
    get:
      summary: 獲取用戶資料
      description: 獲取當前登入用戶的個人資料
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
  /api3/data:
    get:
      summary: 獲取一般資料
      description: 獲取公開的一般資料
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
  /api4/slow:
    get:
      summary: 慢速回應
      description: 模擬需要較長時間處理的請求
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
  /api6/profile:
    post:
      summary: 更新用戶資料
      description: 更新用戶的基本資料
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  user:
                    type: object 